name: Generate coverage badge
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Update coverage badge
        run:  poetry run pytest --cov=aiohttp_catcher --cov-report=term tests | grep TOTAL | GIST_SECRET="${{ secrets.GIST_SECRET }}" poetry run scriptes/extract_coverage.py
